### ISSUE TITLE
Fix navigation stack when a modal submits a form

### ISSUE THREAD

**Issue by jayohms** [hotwired/hotwire-native-android#40]
With the `Navigator` refactor, the form redirect url replaces the root destination. This needs to be fixes so it pushes a new destination onto the root after the modal is dismissed.

See demo app **Load a webpage modally** -> **Submit Form**

**Comment by MichalSznajder** [comment]
FYI also `recede` functionality is affected. After adding to demo app this code:
```
{
  "patterns": [
    "/success$"
  ],
  "properties": {
    "presentation": "pop"
  }
},
 ```
doing *Load a webpage modally* -> *Submit Form* will pop both modal and root view.
   
My workaround for now was a custom `RouteDecisionHandler` that reacts on `recede` and pops only modal:

```
if (uri.path?.startsWith(Locations.RECEDE_PATH) == true) {
    activity.delegate.currentNavigator?.pop()
    return
}
```

I mention it since `recede` is mentioned in [docs](https://native.hotwired.dev/reference/navigation#server-driven-routing-in-rails) and out of the box it is broken for now.

**Comment by jayohms** [comment]
Fixed in https://github.com/hotwired/hotwire-native-android/pull/74
